### ISSUE TITLE
0auth

### ISSUE THREAD

**Issue by spiceysec** [317070/python-twitch-stream#17]
Traceback (most recent call last):
  File "/root/Desktop/python-twitch-stream-master/examples/color.py", line 34, in <module>
    with TwitchBufferedOutputStream(
  File "/usr/local/lib/python3.9/dist-packages/twitchstream/chat.py", line 44, in __enter__
    self.connect()
  File "/usr/local/lib/python3.9/dist-packages/twitchstream/chat.py", line 132, in connect
    s.send('PASS %s\r\n' % self.oauth)
TypeError: a bytes-like object is required, not 'str'

i am lost. can anyone help me set this up?

**Comment by 317070** [comment]
This library was written for python 2.7. 

In python 3, I imagine some strings need to be converted to bytes in order to work well.

**Comment by prophet89** [comment]
hi, i have fixed this problem for myself maybe not the best way to do, diff file is attached for review 

[patch.txt](https://github.com/317070/python-twitch-stream/files/8405128/patch.txt)
